### ISSUE TITLE
Design revisions

### ISSUE THREAD

**Issue by asgrim** [asgrim/godeploy#1]
Need to add any revisions to the design and mark it off as complete so we can start the view building.

The latest revision is the one I did in Dropbox: 110702 design2.psd

If there's no further changes suggested, let's finalise design and get on.

**Comment by ghost** [comment]
I've had a look at the mentioned design .psd and can confirm I'm happy to continue with it.

**Comment by asgrim** [comment]
Good stuff. We'll push ahead with the build then :) I've already made a start on the back end which the latest changes I've pushed to github.
