### ISSUE TITLE
Allow user to specify where debug log is output

### ISSUE THREAD

**Issue by asgrim** [asgrim/godeploy#109]
At the moment, the logfile is output to:

``` php
$logfile = sys_get_temp_dir() . "/godeploy_log";
```

It would be nice if the user could override where the debug log is saved...

**Comment by ghost** [comment]
Where should it be set? In one of the application/configs files?

**Comment by asgrim** [comment]
No it will be in the database, but this is a task for next milestone, you
can filter on the issues list from the right :)
On Oct 24, 2011 9:52 PM, "Simon" <
reply@reply.github.com>
wrote:

**Comment by asgrim** [comment]
Sorry, it is already in the database, we just need a switch on the front end
to make it easier to switch on/off etc.

I'm not 100% sure we need this yet though, so please hold off for now.

**Comment by asgrim** [comment]
Sorry, my bad again. The debug level is already specified in the database but the directory isn't, I didn't read the task properly. This will be a new GD_Config variable.

**Comment by ghost** [comment]
Ok then - should the directory be set from the user interface, or in an .ini file, or is the user going to need to edit the database directly?

**Comment by asgrim** [comment]
GD_Config uses the database for configuration storage, so just in the
database directly for now. We can consider a configuration editor at a later
stage.
