### ISSUE TITLE
Frontend - General structure & build

### ISSUE THREAD

**Issue by asgrim** [asgrim/godeploy#12]
Jon - we'll work on this together one night. Need to do the actual HTML build for this as it's looking pretty ugly at the moment. I suggest we just concentrate on making the login page look good initially, then you'll get an idea of the silly output that Zend_Form makes (with dt/dd etc. as opposed to li's like you're used to...)

**Comment by jonwigham** [comment]
Apart from minor tweaks to the template CSS, this is pretty much done.
