### ISSUE TITLE
Make sure everything is being translated that can be

### ISSUE THREAD

**Issue by asgrim** [asgrim/godeploy#121]
I've noticed e.g. in the home view script that not everything is being translated using the `_e` or `_r` functions where applicable. Ensure all the view scripts, forms and controllers are translating text as appropriate.

**Comment by ghost** [comment]
Seems like a job that I can do.

**Comment by asgrim** [comment]
I was talking to Jon about this earlier and bear in mind that _e and _r stuff with dynamic content (e.g. `_e($somevar)`) will _not_ be picked up by poedit. The text needs to be static.

For example: 

``` php
<h1>Welcome <?php if (count($this->projects) > 0) echo "back "; ?> to GoDeploy</h1>
```

should become

``` php
<?php if(count($this->projects) > 0): ?>
    <h1><? _e("Welcome back to GoDeploy"); ?></h1>
<?php else: ?>
    <h1><? _e("Welcome to GoDeploy"); ?></h1>
<?php endif; ?>
```

**Comment by ghost** [comment]
Do static image alt tags, link titles etc. need translating?

**Comment by asgrim** [comment]
Yep may as well :)

**Comment by asgrim** [comment]
If you have started this please tag it with "in progress"

**Comment by ghost** [comment]
yar ok!
