### ISSUE TITLE
If you have a database on another host

### ISSUE THREAD

**Issue by Keloran** [asgrim/godeploy#125]
If you have your database on another machine than the one your hosting on you can install

here is the line you need to change
$this->Exec("mysql -u{$this->_username} -p{$this->_password} --database={$this->_database} < \"{$script}\"");

and this is what you want
$this->Exec("mysql -u{$this->_username} -p{$this->_password} -h{$this->_hostname} -D{$this->_database} < \"{$script}\"");

that fixes the problem of not having it on the same host, obviouslly you need to set the default option to "localhost" for hostname though

**Comment by asgrim** [comment]
Hi Keloran - thanks for your report/suggestion, that's a good idea. We'll put this into the next milestone :)

**Comment by asgrim** [comment]
For anyone potentially working on this, this line is in GD_Db_Admin - we should also change this for the DB update as well as install (same file).

The only other issue I can see with this is that if mysql is not installed on the same machine - i.e. they can't run mysql command on the local machine to connect to the remote server...
