### ISSUE TITLE
Ability to change slug for a project

### ISSUE THREAD

**Issue by asgrim** [asgrim/godeploy#142]
I would like to be able to change the slug of project. For example I might want project name "Somesite.co.uk" but want the slug to be just "somesite" and not "somesitecouk". It's possible to hack it in the database so I don't think it should cause any issues...

**Comment by ghost** [comment]
Question: MAL_Util_TextFormatting::MakeSlug() is used to change a string to an acceptable format for the slug, but we'll need an equivalent to switch it back. I guess I'll make a commit to MAL?

**Comment by asgrim** [comment]
Why would we need to switch it back?

**Comment by ghost** [comment]
If I enter "This is a string", it gets converted to "this-is-a-string". When this gets output again to the form to be edited, the field contains "this-is-a-string" as that is what was stored in db. The form then tries to convert it again - this time to "thisisastring".

**Comment by asgrim** [comment]
Yep sure make a MAL commit then :)

**Comment by ghost** [comment]
ok!

**Comment by ghost** [comment]
Resolved - it has been decided to not implement this issue at present.
