### ISSUE TITLE
Auto-copy version hashes

### ISSUE THREAD

**Issue by mduk** [asgrim/godeploy#157]
Clicking on a version hash in the deployment history or deployment details pages could automatically select and copy the hash to the clipboard?

In Chrome at least, double clicking on the hash on the details page also selects the contents of the <dt> label, resulting in "To388f6f180f88c7ad54ccbcbcab4723cc7ee9027a" and me having to specifically mark and select the hash manually.

**Comment by asgrim** [comment]
https://github.com/mojombo/clippy could be used for this, github use it for their copy to clipboard thingies.
