### ISSUE TITLE
Backend for deployment running page

### ISSUE THREAD

**Issue by asgrim** [asgrim/godeploy#17]
Similar to deployment preview page, but this needs some AJAXification to update status of each file as it goes along etc.

**Comment by jonwigham** [comment]
Not sure about AJAXification on this, I'm thinking an iframe and a bit of ob_flush() should do the trick...

**Comment by asgrim** [comment]
Nah cuz all the files to "action" will be listed at the start just like the preview page. I envisage it just updating the status column in the table (html table, not fb table) as it goes along. iframes make me shudder :P I think I'd rather use prototype or jquery for js tho rather than dojo. I don't know dojo well enough :(
