### ISSUE TITLE
Backend for deployment results page

### ISSUE THREAD

**Issue by asgrim** [asgrim/godeploy#18]
Show status of the deployment and what happened etc.
This basically just loads the deployment history record and the file list from the database.

**Comment by ghost** [comment]
What's the difference between this issue and issue 7?

**Comment by asgrim** [comment]
The deployment results page shows the outcome of an individual deployment. The deployment history page should just be a list of the deployments done. The deployments history page will be linked to the results page.

**Comment by ghost** [comment]
Ah right, so the issue 7 job was a simplified list of past deployments and this one will be a page with the deployment's full details, linked to from the history list. I can pick this one up too?

**Comment by asgrim** [comment]
It's actually pretty much done as the preview/running/results pages are more
or less the same. I'll have to review this and see what's still to do...

**Comment by ghost** [comment]
roger!

**Comment by asgrim** [comment]
soz dude - got this done, it was only like 1 line :)
