### ISSUE TITLE
Finish wireframe for profile page

### ISSUE THREAD

**Issue by asgrim** [asgrim/godeploy#2]

**Comment by ghost** [comment]
Uploaded a basic profile page, "profile_2.bmml" to dropbox. The other tabs are more there as placeholders, not fully sure what we'll need up there yet.

**Comment by asgrim** [comment]
I think because we don't really need profiles as such, just a place to change username and password should suffice to be honest, as per our IM chat :P

**Comment by ghost** [comment]
Okie dokie then.
