### ISSUE TITLE
Front end - index page

### ISSUE THREAD

**Issue by asgrim** [asgrim/godeploy#24]
Yo - just thinking about the index page where you're trying to do the login form at the moment. Think it might make more sense to just have the login form and save the stuff that's on there for the "website" when it gets done?

e.g. phpMyAdmin doesn't have all that "salesy" gumpff on the front, it just has the login form and logo. Mebee just do that?

I've styled up the "/home" page though :)

**Comment by asgrim** [comment]
smashed to you Jon :P

**Comment by jonwigham** [comment]
The index now just forwards to auth/login if you're not logged in and /home if you are.

Not much else to do here.

I think the /home page could do with some more work though, but that's a separate task...
