### ISSUE TITLE
In PublicKey->setData, figure out key comment

### ISSUE THREAD

**Issue by asgrim** [asgrim/godeploy#26]
In the GD_Model_PublicKey->setData function we need to parse the public key to get the "comment" on the end and call setComment on ourself to store it in the database.

**Comment by ghost** [comment]
is this 'comment' the comment that is attached to a git commit?

**Comment by asgrim** [comment]
No, this is the comment on the end of an SSH key (normally this is a user@hostname combination or some kind of identifier), for example:

ssh-rsa AAAAB3Nz...0wWQ== james@shinylaptop-ubuntu

The comment should be parsed to be "james@shinylaptop-ubuntu". I am not sure of the format of the RSA key itself - if it does not contain spaces, then this should be straightforward - basically anything after the 2nd space would be the comment. This must be confirmed first though.
