### ISSUE TITLE
Delete more stuff from DB when deleting project

### ISSUE THREAD

**Issue by asgrim** [asgrim/godeploy#27]
At the moment only the public key and project itself get deleted from the database.

We also need to delete:
- Deployments
- Deployment files
- Servers

**Comment by ghost** [comment]
I can do this one.

**Comment by asgrim** [comment]
We also need to remove the appropriate gitcache directory for the project.

**Comment by ghost** [comment]
Could you let me know which class/method you'd like the project deletion code in? Better I get it right first time ;)

**Comment by asgrim** [comment]
Yep there is the delete action in the project settings controller, its already half started, just need to do the other bits. Explore the file in the save project method there is some code to delete a repository.

**Comment by ghost** [comment]
Now that I look at it, it's quite obvious that is the way it should be done, the other 3 methods I created were completely pointless. I must have been sniffing glue or something.

**Comment by asgrim** [comment]
That's the spirit :D

**Comment by ghost** [comment]
This one's done.
