### ISSUE TITLE
Duplication bug adding when projects

### ISSUE THREAD

**Issue by jonwigham** [asgrim/godeploy#36]
When I add a new project, it creates 2 records for it in the db.

Not checked most of the code yet though, so not sure where the duplication is.

**Comment by asgrim** [comment]
Thanks - had a quick look but couldn't reproduce it, although it was probably introduced when I added the git clone functionality. Will look into it further.

**Comment by jonwigham** [comment]
Yeah, I think so - the exception was something about not being able to git clone a repo...

**Comment by ghost** [comment]
I think me and Jon talked about this issue on saturday, and he was able to reproduce it on my laptop too (ubuntu/apache).

**Comment by asgrim** [comment]
Thanks guys - I believe this is related to the git clone failing upon project creation. Are you able to give me the exact Exception message?

**Comment by jonwigham** [comment]
There's a screenshot of the exception and stack trace in dropbox for you.
