### ISSUE TITLE
Permissions bug when creating a project

### ISSUE THREAD

**Issue by jonwigham** [asgrim/godeploy#43]
If the script doesn't have permission to make folders/files on your local drive, it fails when it tries to git clone.

The error produced is "Warning: chdir() [function.chdir]: No such file or directory (errno 2) in D:\dev\apache\GoDeploy\library\GD\Git.php on line 298"

This just needs to be nicified as a form error message.

**Comment by asgrim** [comment]
In theory this shouldn't happen any more! I inadvertently put a check for file_exists on the directory first and if not to create it  first through another issue I was having.

Please can you try reproducing this again, if you can't, please mark it as closed. Cheers!

**Comment by asgrim** [comment]
Going to assume closed.
