### ISSUE TITLE
Add icons to deployments

### ISSUE THREAD

**Issue by asgrim** [asgrim/godeploy#47]
Yo Jonneth, don't know if you already have these, but we need icons for:
- Overall deployment status:
  - Preview
  - Running (I think this should be animated? with CSS3 perhaps? ^_^ )
  - Completed (no errors)
  - Failed
- Each file's status:
  - Not started
  - In progress
  - Completed
  - Failed

Cheers!

**Comment by jonwigham** [comment]
Complete and failed are done

**Comment by jonwigham** [comment]
We can just use the "view" one for preview.

**Comment by jonwigham** [comment]
Waiting's done.

**Comment by jonwigham** [comment]
Running/in progress is done as a gif - feck CSS 3. ;)

**Comment by asgrim** [comment]
#93 - to build these icons into app
