### ISSUE TITLE
Design an ace logo

### ISSUE THREAD

**Issue by asgrim** [asgrim/godeploy#5]

**Comment by ghost** [comment]
Will it be based on the circle/arrow design or a new one?

**Comment by asgrim** [comment]
A new one. We'll get Jon to do a logo.

**Comment by ghost** [comment]
Good idea!

**Comment by jonwigham** [comment]
I've put a couple of mockups for a design tweak in the Dropbox folder... Any thoughts?

**Comment by asgrim** [comment]
Nice - although with the designs I think we've been going down the wrong route, so I've used your design and made a homepage design in 110726_design_home_james.psd . I like the font though, at first I was like eww, but then I was like ahh. Can you add the font to the Dropbox folder as I don't have it though please.

**Comment by jonwigham** [comment]
Yeah, sure. I'll swap you - the font you used for the headings is called "Ubuntu Slanted" or something - which I obviously don't have ;)

**Comment by jonwigham** [comment]
What route were we going down that was wrong then?

**Comment by asgrim** [comment]
As in designing a nice pretty website for it when we don't even have the product built yet :) The font is Ubuntu Titling and I've added it to the DB folder.

**Comment by jonwigham** [comment]
Yeah, got it, cheers. Designing that page was more about getting the brand/template in place to build the pages around though. ;)

**Comment by asgrim** [comment]
Fo sho - we got that down now, so I'm happy to close this off :)
