### ISSUE TITLE
Long operations on form submittals - usability?

### ISSUE THREAD

**Issue by asgrim** [asgrim/godeploy#51]
At the moment on some operations such as submitting the create new project form, which has to git clone a project, can take some time. A user might click the button and think it's broken or spinning out or something.

What I'm thinking is adding a grey overlay with a "please wait" or something that would give feedback to the user that something is actually happening. That would also stop them clicking the submit button multiple times which could muck things up and overload systems or something.

**Comment by asgrim** [comment]
Jon - can I get your opinion on this? Maybe there's a more elegant solution?

**Comment by asgrim** [comment]
I removed the gitCloneOrPull from saveProject and replaced with a delete && gitClone if it's a new project or the repository URL changes.

We don't strictly need the git pull there as the deploy action takes care of doing that when required. I think the overall perceived performance is better if we only do "long" operations when required. We still need to find a better way of handling "long" operations though, such as my suggestion, or maybe someone else has a better idea?

**Comment by jonwigham** [comment]
I've written a script that changes the submit button into one that says "Processing" with a spinning icon when the form is submitted. It also prevents the form being submitted again.

I'll prepare a pull request...

**Comment by jonwigham** [comment]
It's tweakable, but to make the magic happen, all you need to do is add a couple of classNames onto the submit button in the abstract form classs:

$submit = new Zend_Form_Element_Image('btn_submit');
$submit->setImage('/images/buttons/small/save-changes.png');
_$submit->class = "processing_btn size_small";_
