### ISSUE TITLE
When renaming a project, forward to new project slug

### ISSUE THREAD

**Issue by asgrim** [asgrim/godeploy#53]
If you have a project e.g. "my-project" and rename it to "what-project" then after the project has been saved, we need to forward to the new slug "what-project" instead of it forwarding to "my-project"

Steps to reproduce:
- Edit a project
- Rename the project
- Press save

What is expected to happen
- Goes back to the project settings page

What actually happens
- 404

**Comment by ghost** [comment]
Just to update... still working on this, been having some 'fun' with git and merging. Also I'm getting a "Tried setting up SSH authentication but failed. Final error was: [user@]hostname [command]" error when updating existing projects so I'm going to take a look at what I need to do for this first.

**Comment by asgrim** [comment]
In GD_Git class, find the line that says

``` php
$this->runShell("ssh -T -o StrictHostKeyChecking=no {$host}", false);
```

and change to:

``` php
$this->runShell("ssh -T -o StrictHostKeyChecking=no {$host}", false, true);
die();
```

That should give you some debug output, if you could paste that here I can help you with the ssh issue.

**Comment by ghost** [comment]
The SSH issue was because I wasn't putting the url of a valid repository in, so :P

But it still throws a zend error when presented with an incorrect url - should this be a new issue?

**Comment by asgrim** [comment]
What error is it exactly?

**Comment by ghost** [comment]
When something not recognisable at as a git URL is used in the Repository URL field (e.g. I used "moose"), it throws this error: 

Message: Tried setting up SSH authentication but failed. Final error was: [user@]hostname [command]

Stack trace:

0 /var/www/godeploy/library/GD/Git.php(413): GD_Git->sshKeys()
1 /var/www/godeploy/application/controllers/SettingsController.php(188): GD_Git->gitClone()
2 /var/www/godeploy/application/controllers/SettingsController.php(62): SettingsController->saveProject(Object(GD_Model_ProjectsMapper), Object(GD_Model_Project), false, true)
3 /var/www/godeploy/library/Zend/Controller/Action.php(513): SettingsController->indexAction()
4 /var/www/godeploy/library/Zend/Controller/Dispatcher/Standard.php(295): Zend_Controller_Action->dispatch('indexAction')
5 /var/www/godeploy/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
6 /var/www/godeploy/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
7 /var/www/godeploy/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
8 /var/www/godeploy/public/index.php(26): Zend_Application->run()
9 {main}
