### ISSUE TITLE
Improve header and navigation - make it project-orientated

### ISSUE THREAD

**Issue by asgrim** [asgrim/godeploy#54]
We are sacking off the profile page in favour of more project-orientated stuff. Do away with the "Profile" tab and replace with the current project and what things you can do in it (e.g. settings, history, deploy etc.). 

The change password link will be at the footer (part of #48)

**Comment by asgrim** [comment]
When in a project, the navigation should be changed to be Home, History, Settings, Deploy, Logout. The History/Settings/Deploy obviously would only be appropriate when "in" a project.

**Comment by jonwigham** [comment]
I've done the work for this (minus the password - Simon did that - and the removal of the links from the /home page which is in another issue).

James, I'll commit it and make a pull request so you can see. It should be easy enough to adapt if we need to add more things in too.
