### ISSUE TITLE
Build the new "home" page

### ISSUE THREAD

**Issue by asgrim** [asgrim/godeploy#57]
You said you weren't happy with the design of the homepage. If you have some kind of idea lets go through some kind of approval process as before. Dropbox it up and write here and once happy we'll turn this issue into a build issue.

**Comment by jonwigham** [comment]
Massive fail - used the wrong issue id in the commit message! :P That should be #51. :(

**Comment by asgrim** [comment]
As part of this I think there should be a link on the Project name which goes to to the History page. We would then remove the Deployments and Delete links and just have Settings left.

When in a project, the navigation should be changed to be Home, History, Settings, Deploy, Logout. The History/Settings/Deploy obviously would only be appropriate when "in" a project. This should be covered off in #54 though.

Also add a link on the settings page to delete the project.

**Comment by jonwigham** [comment]
Initial mockup is in the DropBox folder - 111010_home.gif...

Any thoughts?

**Comment by asgrim** [comment]
Consistent, good. I don't think the repo URL is needed. Change "Last updated" to "Last deployed". I'm unclear as to what the right hand icon should do? I imagine the magnifying glass ("view") icon would take to history? Would the arrow start a new deployment?

The most common functionality intended is to do deployments, so we should make the primary function to create a new deployment (hence the massive "Deploy" button on the old design), and viewing the deployments a "secondary" action.

**Comment by jonwigham** [comment]
The view one was for the history, and the edit one was for the settings.

On a related note, I don't like the edit icon, so I'm going to redo that.

I'll keep the view icon for the history, and I'll use the new icon there for the settings. I'll also throw in a small "deploy" button.

**Comment by jonwigham** [comment]
That's updated now.

**Comment by asgrim** [comment]
Cool, I'm happy with that if you are. From now on this is a build task :)
