### ISSUE TITLE
Redo "Run Deployment" and "Preview Deployment" buttons

### ISSUE THREAD

**Issue by asgrim** [asgrim/godeploy#58]
These could do with being just "Run" and "Preview" - it looks a bit excessive otherwise.

Also maybe some kind of distinction between them - would it make more sense I think for the "Run" button to be larger perhaps? I'm not sure.

**Comment by jonwigham** [comment]
I've made the buttons just say "Deploy" (why say "run" - the site is called go"deploy" ;)) and "Preview".

The buttons sit next to each other, and the Preview one has inverted colours.
