### ISSUE TITLE
Add deployments history page

### ISSUE THREAD

**Issue by asgrim** [asgrim/godeploy#7]

**Comment by ghost** [comment]
Working on this, but also familiarising myself with git a bit more.

**Comment by asgrim** [comment]
Hows this going buddy?

**Comment by ghost** [comment]
it's coming along, didn't get much time last week, but i have more time to myself this week.

**Comment by asgrim** [comment]
Cool no probs sir

**Comment by ghost** [comment]
Sent a pull request for this.

**Comment by asgrim** [comment]
Simon - I have simplified your function, specifically look at https://github.com/Asgrim/GoDeploy/commit/1876611b6b1ee22050538e9e1a1fada0d7b48460#L10R139 and you'll see how simple using Zend_Db_Table makes things. There's a lot of additions in the commit as well - those are for the joins etc. which are done automatically now so you don't need to do all those crazy joins in the future! :)

**Comment by ghost** [comment]
Ok then Mr Zend Expert :P

By the way, what design pattern do you use for working with the database? It is a specific one, or one you designed yourself?

**Comment by asgrim** [comment]
The Zend Framework one :)

**Comment by ghost** [comment]
I guess that was the obvious answer. 

I think I will have to RTFM a bit more.
