### ISSUE TITLE
Add slug preview to project settings

### ISSUE THREAD

**Issue by asgrim** [asgrim/godeploy#9]
When editing the project name field on /project/test-project/settings page, it would be cool to see the slug auto generated as the project name is typed in.

The back-end auto generates this by doing:

``` php
$slug = strtolower($this->_name);
$slug = preg_replace("/[^0-9a-z]/", "-", $slug);
```

So if we can do the JS equivalent (for display only, don't need to pass it through the Zend_Form) that would be ace.

**Comment by jonwigham** [comment]
Done this. Had to change the regex in the JS and in the PHP though as what's above was a MASSIVE FAILURE. ;)

**Comment by jonwigham** [comment]
I'll include it in the next commit, so this can be closed,
