### ISSUE TITLE
Add icons to deployments

### ISSUE THREAD

**Issue by asgrim** [asgrim/godeploy#93]
Add the icons that Jon designed to the deployments page e.g. for Previewing/Running/Completed/Failed etc.

**Comment by asgrim** [comment]
Why am I flid???

**Comment by jonwigham** [comment]
Cos you pasted a link to godeploy.localhost into a comment! ;)

**Comment by asgrim** [comment]
Yes I wanted to paste something temporarily :P

**Comment by jonwigham** [comment]
Just pulled it - that is fucking sexy!

There's a couple of things we could do to make it even sexier though...

**Comment by asgrim** [comment]
OK - can you open a new issue for v0.2 release as I'd like to feature-freeze this release now.
