### ISSUE TITLE
History RSS link exception

### ISSUE THREAD

**Issue by jonwigham** [asgrim/godeploy#99]
The view, JSON and CSV pages all look fine, but the RSS link doesn't work for me.

I've put a screenshot of it in DropBox for you. :)

**Comment by asgrim** [comment]
Looks like because this is using `$_SERVER["SCRIPT_URI"]` to get the URL (L103 in HistoryController.php) and it's not set on your system. We should find a more reliable way of doing that. Fancy taking this on?

**Comment by asgrim** [comment]
Jon can you please pull and confirm my change has fixed this bug. If so - please close this issue.

**Comment by jonwigham** [comment]
Yeah, that seems to have fixed it. Good job. :)
